# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Diegovieiraeti
tagline:          'Página pessoal'
description:      ''
url:              http://diegovieira.eti.br

author:
  name:           'Diego Vieira'
  url:            http://diegovieira.eti.br

paginate:         5

# Custom vars
version:          0.0.5

github:
  repo:           https://github.com/diegovieiraeti/site
